---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Incident creation"
      solveButton: false
    - name: module-02
      label: "Attaching a problem"
      solveButton: false
    - name: module-03
      label: "Root cause, fix and close"
      solveButton: false
    - name: module-04
      label: "Query and update ServiceNow"
      solveButton: false
    - name: module-05
      label: "Query and update records"
      solveButton: false
    - name: module-06
      label: "Use ServiceNow as an inventory"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
    external: false
  - name: vscode
    url: https://control-${guid}.${domain}:4444
    external: false
  - name: ">_ control"
    url: /wetty
  - name: ">_ node01"
    url: /wetty_node01
  - name: ">_ node02"
    url: /wetty_node02
